// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvZZKBW7tcEN0-kzwwYz1oG_-0q5WN2g',
    appId: '1:161108388125:web:254b7134f4593cb373d9f4',
    messagingSenderId: '161108388125',
    projectId: 'smart-vote-65954',
    authDomain: 'smart-vote-65954.firebaseapp.com',
    storageBucket: 'smart-vote-65954.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3OOvMblW1bRc-4paRTlpBgYRPtOtsN4',
    appId: '1:161108388125:android:e24dea832a23af8973d9f4',
    messagingSenderId: '161108388125',
    projectId: 'smart-vote-65954',
    storageBucket: 'smart-vote-65954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbi51gVYZC1qoDWYqVBLfjSAiX7AM-us',
    appId: '1:161108388125:ios:4c26c57be491361273d9f4',
    messagingSenderId: '161108388125',
    projectId: 'smart-vote-65954',
    storageBucket: 'smart-vote-65954.appspot.com',
    iosBundleId: 'com.example.smartVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbi51gVYZC1qoDWYqVBLfjSAiX7AM-us',
    appId: '1:161108388125:ios:44580b1fa3eefc4473d9f4',
    messagingSenderId: '161108388125',
    projectId: 'smart-vote-65954',
    storageBucket: 'smart-vote-65954.appspot.com',
    iosBundleId: 'com.example.smartVote.RunnerTests',
  );
}
